-- Generated by Enshrouded Mod Hub Control Center
-- DO NOT EDIT DIRECTLY

local function safe_require(name)
    local ok, result = pcall(require, name)
    if not ok then print('[ModBrain ERROR] Config load failed: ' .. tostring(name) .. ' :: ' .. tostring(result)); return {} end
    return result or {}
end

local Brain = {
    Modules = {},
    Configs = {},
    Context = {
        Log = function(msg) print('[ModBrain] ' .. tostring(msg)) end,
        LogWarn = function(msg) print('[ModBrain WARN] ' .. tostring(msg)) end,
        LogError = function(msg) print('[ModBrain ERROR] ' .. tostring(msg)) end,
        GetResources = function(typeName) if game and game.assets and game.assets.get_resources_by_type then return game.assets.get_resources_by_type(typeName) or {} end return {} end,
    }
}

Brain.Configs['loot_and_chests'] = safe_require('Config.loot_and_chests')
Brain.Configs['music_and_instruments'] = safe_require('Config.music_and_instruments')
Brain.Configs['progression_balancing'] = safe_require('Config.progression_balancing')
Brain.Configs['survival_qol'] = safe_require('Config.survival_qol')
Brain.Configs['terraforming_and_mining'] = safe_require('Config.terraforming_and_mining')
Brain.Configs['world_and_difficulty'] = safe_require('Config.world_and_difficulty')

-- Module: loot_and_chests
local ok, err = pcall(function()
    local modFunc = function()
        -- ============================================================================
        -- Module: Loot Tables, Chests & Drop Rates (loot_and_chests)
        -- Target: keen::LootableItemsResource, keen::fishing::TrashLootTableResource
        -- ============================================================================
        
        local Module = {}
        
        function Module.OnInit(config, context)
            context.Log("Applying Loot Table & Drop Rate sliding scale modifications...")
        
            local lootBoost = config.legendary_drop_rate_boost or 1.0
            local trashRatePct = config.trash_fishing_probability_pct
        
            -- 1. Lootable Items Rarity Drop Rates Slider (1.0x to 10.0x)
            if lootBoost > 1.0 then
                local lootList = context.GetResources("keen::LootableItemsResource")
                if lootList and #lootList > 0 then
                    for _, res in ipairs(lootList) do
                        local lt = res and res.data
                        if lt and lt.globalRarityDropRates then
                            for k, rate in pairs(lt.globalRarityDropRates) do
                                if type(rate) == "number" then
                                    lt.globalRarityDropRates[k] = math.min(1.0, rate * lootBoost)
                                end
                            end
                        end
                    end
                    context.Log("Boosted global rarity drop rates by " .. tostring(lootBoost) .. "x!")
                end
            end
        
            -- 2. Trash Fishing Probability Slider (0% to 100%)
            if trashRatePct ~= nil and trashRatePct < 100 then
                local trashTables = context.GetResources("keen::fishing::TrashLootTableResource")
                if trashTables and #trashTables > 0 then
                    local factor = trashRatePct / 100.0
                    for _, res in ipairs(trashTables) do
                        local tt = res and res.data
                        if tt and tt.entries and type(tt.entries) == "table" then
                            for _, entry in ipairs(tt.entries) do
                                if entry.weight then
                                    entry.weight = entry.weight * factor
                                end
                            end
                        end
                    end
                    context.Log("Scaled trash fishing weights to " .. tostring(trashRatePct) .. "%!")
                end
            end
        end
        
        return Module
    end
    local instance = modFunc()
    if instance and instance.OnInit then instance.OnInit(Brain.Configs['loot_and_chests'] or {}, Brain.Context) end
    Brain.Modules['loot_and_chests'] = instance
end)
if not ok then
    Brain.Context.LogError('Module loot_and_chests failed safely: ' .. tostring(err))
end

-- Module: music_and_instruments
local ok, err = pcall(function()
    local modFunc = function()
        -- ============================================================================
        -- Module: Music, Instruments & Campfire Songs (music_and_instruments)
        -- Target: keen::SamplerInstrumentResource, keen::BalancingTable
        -- ============================================================================
        
        local Module = {}
        
        function Module.OnInit(config, context)
            context.Log("Applying Music & Instrument modifications...")
        
            -- 1. Comfort Buff from Instruments in BalancingTable
            if config.instrument_comfort_buff_mult and config.instrument_comfort_buff_mult > 1.0 then
                local tables = context.GetResources("keen::BalancingTable")
                if tables and #tables > 0 then
                    for _, res in ipairs(tables) do
                        local d = res and res.data
                        if d then
                            if d.maximumTotalMusicComfortBuff then
                                d.maximumTotalMusicComfortBuff = math.floor(d.maximumTotalMusicComfortBuff * config.instrument_comfort_buff_mult)
                            end
                        end
                    end
                    context.Log("Scaled maximum instrument comfort buffs in BalancingTable!")
                end
            end
        
            -- 2. Volume Boost on Instruments
            if config.instrument_volume_boost and config.instrument_volume_boost > 1.0 then
                local instruments = context.GetResources("keen::SamplerInstrumentResource")
                if instruments and #instruments > 0 then
                    for _, res in ipairs(instruments) do
                        local inst = res and res.data
                        if inst and inst.volume then
                            inst.volume = math.min(2.0, inst.volume * config.instrument_volume_boost)
                        end
                    end
                    context.Log("Enhanced acoustic volume for " .. tostring(#instruments) .. " instruments!")
                end
            end
        end
        
        return Module
    end
    local instance = modFunc()
    if instance and instance.OnInit then instance.OnInit(Brain.Configs['music_and_instruments'] or {}, Brain.Context) end
    Brain.Modules['music_and_instruments'] = instance
end)
if not ok then
    Brain.Context.LogError('Module music_and_instruments failed safely: ' .. tostring(err))
end

-- Module: progression_balancing
local ok, err = pcall(function()
    local modFunc = function()
        -- ============================================================================
        -- Module: Progression & Character Balancing (progression_balancing)
        -- Target: keen::BalancingTable
        -- ============================================================================
        
        local Module = {}
        
        function Module.OnInit(config, context)
            context.Log("Applying Progression & Character Balancing modifications...")
        
            local tables = context.GetResources("keen::BalancingTable")
            if not tables or #tables == 0 then
                context.LogWarn("No keen::BalancingTable resources found!")
                return
            end
        
            for _, res in ipairs(tables) do
                local d = res and res.data
                if d then
                    -- 1. Level Caps
                    if config.player_level_cap and config.player_level_cap > 25 then
                        d.playerLevelCap = config.player_level_cap
                        d.playerLevelMax = math.max(d.playerLevelMax or 25, config.player_level_cap)
                    end
        
                    if config.item_level_cap and config.item_level_cap > 50 then
                        d.itemLevelCap = config.item_level_cap
                    end
        
                    -- 2. Shroud Fog Resistance (Timer)
                    if config.shroud_fog_resistance_multiplier and config.shroud_fog_resistance_multiplier > 1.0 then
                        local baseFog = d.playerBaseFogResistance or 300
                        d.playerBaseFogResistance = math.floor(baseFog * config.shroud_fog_resistance_multiplier)
                    end
        
                    -- 3. Base Attribute Pools
                    if config.player_base_health and config.player_base_health > 100 then
                        d.playerBaseHealth = config.player_base_health
                    end
        
                    if config.player_base_stamina and config.player_base_stamina > 100 then
                        d.playerBaseStamina = config.player_base_stamina
                    end
        
                    if config.player_base_mana and config.player_base_mana > 100 then
                        d.playerBaseMana = config.player_base_mana
                    end
        
                    -- 4. Progression Rates
                    if config.skill_points_per_level and config.skill_points_per_level > 1 then
                        d.skillPointsPerLevel = config.skill_points_per_level
                    end
        
                    if config.ap_per_flame_level and config.ap_per_flame_level > 1 then
                        d.apPerFlameLevel = config.ap_per_flame_level
                    end
        
                    -- 5. Critical Hits
                    if config.base_crit_chance then
                        d.baseCritChance = config.base_crit_chance / 100.0
                    end
        
                    if config.crit_bonus_multiplier and config.crit_bonus_multiplier > 1.5 then
                        d.critBonus = config.crit_bonus_multiplier
                    end
        
                    -- 6. Altars
                    if config.altars_per_flame_level and config.altars_per_flame_level > 1 and d.altarsPerFlameLevel then
                        for i = 1, #d.altarsPerFlameLevel do
                            d.altarsPerFlameLevel[i] = math.min(255, config.altars_per_flame_level)
                        end
                    end
        
                    context.Log("Patched keen::BalancingTable (GUID: " .. tostring(res.guid) .. ") successfully!")
                end
            end
        end
        
        return Module
    end
    local instance = modFunc()
    if instance and instance.OnInit then instance.OnInit(Brain.Configs['progression_balancing'] or {}, Brain.Context) end
    Brain.Modules['progression_balancing'] = instance
end)
if not ok then
    Brain.Context.LogError('Module progression_balancing failed safely: ' .. tostring(err))
end

-- Module: survival_qol
local ok, err = pcall(function()
    local modFunc = function()
        -- ============================================================================
        -- Module: Survival QoL & Utility (survival_qol)
        -- Author: JoelT
        -- Engine Resource Mappings verified against Keen KFC GameSettings
        -- ============================================================================
        
        local Module = {}
        
        local function setPresetValue(container, key, val)
            if not container then return false end
            local ok, applied = pcall(function()
                local field = container[key]
                if field == nil then return false end
                if type(field) == "userdata" or type(field) == "table" then
                    local valueOk, current = pcall(function() return field.value end)
                    if valueOk and current ~= nil then
                        local writeOk = pcall(function() field.value = val end)
                        return writeOk
                    end
                    return false
                end
                local writeOk = pcall(function() container[key] = val end)
                return writeOk
            end)
            return ok and applied == true
        end
        
        function Module.OnInit(config, context)
            context.Log("Initializing Survival QoL...")
        
            -- 1. Stack Size Tweaks (keen::ItemInfo -> maxStackSize)
            if config.stack_multiplier and config.stack_multiplier > 1 then
                local items = context.GetResources("keen::ItemInfo")
                local changed = 0
                for _, it in ipairs(items) do
                    local d = it and it.data
                    local cur = d and d.maxStackSize
                    if type(cur) == "number" and cur > 1 then
                        d.maxStackSize = math.min(65535, math.floor(cur * config.stack_multiplier))
                        changed = changed + 1
                    end
                end
                context.Log("Updated maxStackSize for " .. tostring(changed) .. " items!")
            end
        
            -- 2. Shroud Timer Multiplier (keen::BalancingTable -> playerBaseFogResistance)
            if config.shroud_time_multiplier and config.shroud_time_multiplier > 1 then
                local TARGET_BALANCING_GUID = "82706b40-61b1-4b8f-8b23-dcec6971bda1"
                local balancingTables = context.GetResources("keen::BalancingTable")
                for _, res in ipairs(balancingTables) do
                    if tostring(res.guid) == TARGET_BALANCING_GUID and res.data then
                        local base = res.data.playerBaseFogResistance or 300
                        res.data.playerBaseFogResistance = base * config.shroud_time_multiplier
                        context.Log("Shroud Time multiplied: " .. tostring(base) .. " -> " .. tostring(res.data.playerBaseFogResistance))
                        break
                    end
                end
            end
        
            -- 3. Game Settings Tweaks (Stamina & Durability via GameSettingsPresetsResource & FbUiBundle)
            local presetResList = context.GetResources("keen::GameSettingsPresetsResource")
            local uiResList = context.GetResources("keen::FbUiBundle")
        
            if presetResList and #presetResList > 0 and presetResList[1].data then
                local presets = presetResList[1].data
                local ui = (uiResList and #uiResList > 0 and uiResList[1].data) or nil
        
                -- Infinite Durability Toggle
                if config.infinite_durability then
                    setPresetValue(presets.minValues, "enableDurability", false)
                    setPresetValue(presets.maxValues, "enableDurability", false)
                    if ui and ui.difficultySettings and ui.difficultySettings.settingValues then
                        ui.difficultySettings.settingValues["enableDurability"] = false
                    end
                    context.Log("GameSettings: Durability loss DISABLED.")
                end
        
                -- Stamina Drain Reduction / Zero Stamina
                if config.stamina_cost_reduction and config.stamina_cost_reduction > 0 then
                    -- 0.0 = zero stamina consumption
                    local staminaFactor = math.max(0.0, 1.0 - (config.stamina_cost_reduction / 100.0))
                    if config.stamina_cost_reduction >= 100 then
                        staminaFactor = 0.0
                    end
                    setPresetValue(presets.minValues, "playerStaminaFactor", staminaFactor)
                    setPresetValue(presets.maxValues, "playerStaminaFactor", staminaFactor)
                    if ui and ui.difficultySettings and ui.difficultySettings.settingValues then
                        ui.difficultySettings.settingValues["playerStamina"] = staminaFactor
                    end
                    context.Log("GameSettings: playerStaminaFactor set to " .. tostring(staminaFactor))
                end
            end
        end
        
        return Module
    end
    local instance = modFunc()
    if instance and instance.OnInit then instance.OnInit(Brain.Configs['survival_qol'] or {}, Brain.Context) end
    Brain.Modules['survival_qol'] = instance
end)
if not ok then
    Brain.Context.LogError('Module survival_qol failed safely: ' .. tostring(err))
end

-- Module: terraforming_and_mining
local ok, err = pcall(function()
    local modFunc = function()
        -- ============================================================================
        -- Module: Terraforming, Mining & Flora Density (terraforming_and_mining)
        -- Target: keen::TerraformingEfficiencyRegistryResource
        -- ============================================================================
        
        local Module = {}
        
        function Module.OnInit(config, context)
            context.Log("Applying Terraforming & Mining Efficiency modifications...")
        
            local terraList = context.GetResources("keen::TerraformingEfficiencyRegistryResource")
            if not terraList or #terraList == 0 then
                context.LogWarn("No keen::TerraformingEfficiencyRegistryResource found!")
                return
            end
        
            if config.terraforming_speed_multiplier and config.terraforming_speed_multiplier > 1.0 then
                for _, res in ipairs(terraList) do
                    local d = res and res.data
                    if d and d.terrainConfigs and type(d.terrainConfigs) == "table" then
                        for _, cfg in ipairs(d.terrainConfigs) do
                            if cfg.efficiency then
                                cfg.efficiency = cfg.efficiency * config.terraforming_speed_multiplier
                            end
                        end
                    end
                end
                context.Log("Multiplied terraforming voxel efficiency by " .. tostring(config.terraforming_speed_multiplier) .. "x!")
            end
        end
        
        return Module
    end
    local instance = modFunc()
    if instance and instance.OnInit then instance.OnInit(Brain.Configs['terraforming_and_mining'] or {}, Brain.Context) end
    Brain.Modules['terraforming_and_mining'] = instance
end)
if not ok then
    Brain.Context.LogError('Module terraforming_and_mining failed safely: ' .. tostring(err))
end

-- Module: world_and_difficulty
local ok, err = pcall(function()
    local modFunc = function()
        -- ============================================================================
        -- Module: World Rules & Difficulty Tuning (world_and_difficulty)
        -- Target: keen::GameSettingsPresetsResource, keen::FbUiBundle
        -- ============================================================================
        
        local Module = {}
        
        local function setField(obj, key, val)
            if not obj then return false end
            local ok, applied = pcall(function()
                local f = obj[key]
                if f == nil then return false end
                if type(f) == "userdata" or type(f) == "table" then
                    local valueOk, current = pcall(function() return f.value end)
                    if valueOk and current ~= nil then
                        local writeOk = pcall(function() f.value = val end)
                        return writeOk
                    end
                    return false
                end
                local writeOk = pcall(function() obj[key] = val end)
                return writeOk
            end)
            return ok and applied == true
        end
        
        function Module.OnInit(config, context)
            context.Log("Applying World Rules & Game Settings modifications...")
        
            local presetResList = context.GetResources("keen::GameSettingsPresetsResource")
            local uiResList = context.GetResources("keen::FbUiBundle")
        
            if not presetResList or #presetResList == 0 then
                context.LogWarn("keen::GameSettingsPresetsResource not found!")
                return
            end
        
            local presetsObj = presetResList[1].data
            local uiObj = (uiResList and #uiResList > 0 and uiResList[1].data) or nil
        
            local targets = {}
            if presetsObj then
                if presetsObj.minValues then table.insert(targets, presetsObj.minValues) end
                if presetsObj.maxValues then table.insert(targets, presetsObj.maxValues) end
                if presetsObj.presets and type(presetsObj.presets) == "table" then
                    for _, p in ipairs(presetsObj.presets) do
                        if p and p.settings then table.insert(targets, p.settings) end
                    end
                end
            end
        
            for _, target in ipairs(targets) do
                -- Combat & Enemies
                if config.enemy_damage_factor then setField(target, "enemyDamageFactor", config.enemy_damage_factor) end
                if config.enemy_health_factor then setField(target, "enemyHealthFactor", config.enemy_health_factor) end
                if config.boss_damage_factor then setField(target, "bossDamageFactor", config.boss_damage_factor) end
                if config.boss_health_factor then setField(target, "bossHealthFactor", config.boss_health_factor) end
                if config.pacify_all_enemies ~= nil then setField(target, "pacifyAllEnemies", config.pacify_all_enemies) end
        
                -- Progression & XP
                if config.experience_combat_factor then setField(target, "experienceCombatFactor", config.experience_combat_factor) end
                if config.experience_mining_factor then setField(target, "experienceMiningFactor", config.experience_mining_factor) end
        
                -- Harvesting & Economy
                if config.resource_drop_stack_factor then setField(target, "resourceDropStackAmountFactor", config.resource_drop_stack_factor) end
                if config.mining_damage_factor then setField(target, "miningDamageFactor", config.mining_damage_factor) end
                if config.plant_growth_speed_factor then setField(target, "plantGrowthSpeedFactor", config.plant_growth_speed_factor) end
                if config.factory_production_speed_factor then setField(target, "factoryProductionSpeedFactor", config.factory_production_speed_factor) end
        
                -- Mechanics & Durability
                if config.disable_durability then setField(target, "enableDurability", false) end
                if config.food_buff_duration_factor then setField(target, "foodBuffDurationFactor", config.food_buff_duration_factor) end
                if config.player_health_factor then setField(target, "playerHealthFactor", config.player_health_factor) end
                if config.player_mana_factor then setField(target, "playerManaFactor", config.player_mana_factor) end
                if config.player_stamina_factor then setField(target, "playerStaminaFactor", config.player_stamina_factor) end
                if config.player_body_heat_factor then setField(target, "playerBodyHeatFactor", config.player_body_heat_factor) end
                if config.player_diving_time_factor then setField(target, "playerDivingTimeFactor", config.player_diving_time_factor) end
                if config.enable_starving_debuff ~= nil then setField(target, "enableStarvingDebuff", config.enable_starving_debuff) end
                if config.shroud_time_factor then setField(target, "shroudTimeFactor", config.shroud_time_factor) end
                if config.enable_glider_turbulences ~= nil then setField(target, "enableGliderTurbulences", config.enable_glider_turbulences) end
                if config.weather_frequency then setField(target, "weatherFrequency", config.weather_frequency) end
                if config.fishing_difficulty then setField(target, "fishingDifficulty", config.fishing_difficulty) end
                if config.enemy_stamina_factor then setField(target, "enemyStaminaFactor", config.enemy_stamina_factor) end
                if config.enemy_perception_range_factor then setField(target, "enemyPerceptionRangeFactor", config.enemy_perception_range_factor) end
                if config.threat_bonus then setField(target, "threatBonus", config.threat_bonus) end
                if config.random_spawner_amount then setField(target, "randomSpawnerAmount", config.random_spawner_amount) end
                if config.aggro_pool_amount then setField(target, "aggroPoolAmount", config.aggro_pool_amount) end
                if config.day_time_duration then setField(target, "dayTimeDuration", config.day_time_duration) end
                if config.night_time_duration then setField(target, "nightTimeDuration", config.night_time_duration) end
                if config.taming_startle_repercussion then setField(target, "tamingStartleRepercussion", config.taming_startle_repercussion) end
                if config.curse_modifier then setField(target, "curseModifier", config.curse_modifier) end
            end
        
            -- Sync UI Bundle difficulty settings if present
            if uiObj and uiObj.difficultySettings and uiObj.difficultySettings.settingValues then
                local sv = uiObj.difficultySettings.settingValues
                if config.disable_durability then sv["enableDurability"] = false end
                if config.pacify_all_enemies ~= nil then sv["pacifyAllEnemies"] = config.pacify_all_enemies end
            end
        
            context.Log("World Rules & Difficulty settings successfully applied to game presets!")
        end
        
        return Module
    end
    local instance = modFunc()
    if instance and instance.OnInit then instance.OnInit(Brain.Configs['world_and_difficulty'] or {}, Brain.Context) end
    Brain.Modules['world_and_difficulty'] = instance
end)
if not ok then
    Brain.Context.LogError('Module world_and_difficulty failed safely: ' .. tostring(err))
end
