-- Generated by Enshrouded Control Center behavior research.
local resource_name = 'keen::ecs::GameSettings'
local field_name = 'playerManaFactor'
local test_value = 2.0
local ok, resources = pcall(function() return game.assets.get_resources_by_type(resource_name) or {} end)
if not ok or #resources == 0 then
    print('[CC-BEHAVIOR] ' .. resource_name .. '.' .. field_name .. '|resource_not_loaded')
else
    local resource = resources[1]
    local read_ok, original = pcall(function() return resource.data[field_name] end)
    local write_ok, write_error = pcall(function() resource.data[field_name] = test_value end)
    local verify_ok, applied = pcall(function() return resource.data[field_name] end)
    print('[CC-BEHAVIOR] ' .. resource_name .. '.' .. field_name .. '|original=' .. tostring(original) .. '|write=' .. tostring(write_ok) .. '|applied=' .. tostring(applied) .. '|verify=' .. tostring(verify_ok))
    if not write_ok then print('[CC-BEHAVIOR] error=' .. tostring(write_error)) end
end
