-- Generated by Enshrouded Control Center.
-- This module is research-only until its donor schema and runtime evidence are verified.
local REQUIRED_API = "assets.register_resource"
local RESOURCE_TYPE = "keen::ItemInfo"
local DONOR_ID = 2940001508
local kfc = require('kfc_content_registry')

local function log(kind, value)
    print("[CC-GENERATED:visual_substitution_bed_20260927] " .. kind .. "|" .. tostring(value or ""))
end

local function resources(type_name)
    local ok, result = pcall(function() return game.assets.get_resources_by_type(type_name) or {} end)
    if not ok then log("ERROR", type_name .. "|" .. tostring(result)); return {} end
    return result
end

-- EML executes mod.lua as a top-level patch script. Keep the generated
-- operations at module load time, matching the verified furniture probes.
do
    log("CAPABILITY_REQUIRED", REQUIRED_API)
    log("RESOURCE_TYPE", RESOURCE_TYPE)
    -- Donor lookup and registration must be implemented only after validation.
    local initial_items = resources(RESOURCE_TYPE)
    local donor
    for _, resource in pairs(initial_items) do
        if resource and resource.data then
            log("DONOR_CANDIDATE", tostring(resource.guid))
            if nil ~= nil and tostring(resource.guid) == nil then
                log("DONOR_MATCH", tostring(resource.guid))
                donor = resource
            end
        end
    end
    log("DONOR_SCAN_DONE", tostring(donor ~= nil))
    if not DONOR_ID then log("BLOCKED", "donor_id_required"); return {} end
    if not donor then log("BLOCKED", "donor_not_found"); return {} end
    local ok_clone, clone_or_error = pcall(function()
        return game.assets.register_resource(donor.data, 'keen::ItemInfo')
    end)
    if not ok_clone or not clone_or_error then log("ERROR", "clone_failed|" .. tostring(clone_or_error)); return {} end
    local clone = clone_or_error
    clone.data.itemId.value = 3987654402
    local item_registry
    for _, candidate in pairs(game.assets.get_resources_by_type('keen::ItemRegistryResource') or {}) do
        if candidate and candidate.data and candidate.data.itemRefs then
            item_registry = candidate
            break
        end
    end
    if item_registry then
        clone.data.objectId = clone.guid
        table.insert(item_registry.data.itemRefs, clone)
        if item_registry.data.dbgNames then
            table.insert(item_registry.data.dbgNames, clone.data.debugName)
        end
    end
    -- RESEARCH-ONLY: model customization is recorded but not applied until runtime evidence exists.
    clone.data["source"] = "research-icon-guid"
    log("CLONED_ITEM", 3987654402)


end

return {}
