-- Generated by Enshrouded Control Center KFC Research Lab.
-- Reversible scalar write/readback/revert probe.
local BUILD = '1076226'
local function log(result) print('[CC-WRITE-RESEARCH] ' .. result) end
local function test(resource_name, field_name, candidate_id, kind)
    local ok, resources = pcall(function() return game.assets.get_resources_by_type(resource_name) or {} end)
    if not ok or #resources == 0 then log(candidate_id .. '|resource_not_loaded'); return end
    local resource = resources[1]
    local read_ok, original = pcall(function() return resource.data[field_name] end)
    if not read_ok then log(candidate_id .. '|read_error|' .. tostring(original)); return end
    local test_value = original
    if kind == 'boolean' then test_value = not original end
    if kind == 'number' then test_value = original + 0.125 end
    if kind == 'integer' then test_value = original + 1 end
    local write_ok, write_error = pcall(function() resource.data[field_name] = test_value end)
    if not write_ok then log(candidate_id .. '|write_error|' .. tostring(write_error)); return end
    local readback_ok, readback = pcall(function() return resource.data[field_name] end)
    local restore_ok, restore_error = pcall(function() resource.data[field_name] = original end)
    local restored_ok, restored = pcall(function() return resource.data[field_name] end)
    log(table.concat({candidate_id, 'write=' .. tostring(write_ok), 'readback=' .. tostring(readback_ok), tostring(readback), 'restore=' .. tostring(restore_ok), 'restored=' .. tostring(restored_ok), tostring(restored)}, '|'))
    if not restore_ok then log(candidate_id .. '|restore_error|' .. tostring(restore_error)) end
end
log('BEGIN|build=' .. BUILD)
test('keen::BalancingTable', 'advancedPerkCostNominator', 'keen::BalancingTable.advancedPerkCostNominator', 'number')
test('keen::BalancingTable', 'advancedPerkCostStartLevel', 'keen::BalancingTable.advancedPerkCostStartLevel', 'integer')
test('keen::BalancingTable', 'altarLevelMax', 'keen::BalancingTable.altarLevelMax', 'integer')
test('keen::BalancingTable', 'apPerFlameLevel', 'keen::BalancingTable.apPerFlameLevel', 'integer')
test('keen::BalancingTable', 'baseCritChance', 'keen::BalancingTable.baseCritChance', 'number')
test('keen::BalancingTable', 'buffReapplyPercentage', 'keen::BalancingTable.buffReapplyPercentage', 'number')
test('keen::BalancingTable', 'critBonus', 'keen::BalancingTable.critBonus', 'number')
test('keen::BalancingTable', 'damageBoostFlame', 'keen::BalancingTable.damageBoostFlame', 'number')
test('keen::BalancingTable', 'damageMod2Handed', 'keen::BalancingTable.damageMod2Handed', 'number')
test('keen::BalancingTable', 'damageScalePerAttributePoint', 'keen::BalancingTable.damageScalePerAttributePoint', 'number')
test('keen::BalancingTable', 'disableFreezingBaseLevel', 'keen::BalancingTable.disableFreezingBaseLevel', 'integer')
test('keen::BalancingTable', 'durabilityGrowth', 'keen::BalancingTable.durabilityGrowth', 'number')
test('keen::BalancingTable', 'durabilityLossCap', 'keen::BalancingTable.durabilityLossCap', 'integer')
test('keen::BalancingTable', 'durabilityStart', 'keen::BalancingTable.durabilityStart', 'number')
test('keen::BalancingTable', 'expectedBaseDamageFactor', 'keen::BalancingTable.expectedBaseDamageFactor', 'number')
test('keen::BalancingTable', 'flameLevelMax', 'keen::BalancingTable.flameLevelMax', 'integer')
test('keen::BalancingTable', 'freezeDurationFactor', 'keen::BalancingTable.freezeDurationFactor', 'number')
test('keen::BalancingTable', 'freezeDurationOffset', 'keen::BalancingTable.freezeDurationOffset', 'number')
test('keen::BalancingTable', 'groupSizeXpDamper', 'keen::BalancingTable.groupSizeXpDamper', 'number')
test('keen::BalancingTable', 'groupSizeXpDamperModMin', 'keen::BalancingTable.groupSizeXpDamperModMin', 'number')
log('END|build=' .. BUILD)
