"""Safe, local Enshrouded Mod Hub composition and installation service.

This module deliberately owns only the Mod Hub package files.  It never copies
or replaces an EML loader/proxy DLL and never touches third-party mod folders.
"""
from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Iterable, Optional

from .platform_services import ModuleGraphService, RuntimeHealthService


class InstallerError(RuntimeError):
    pass


@dataclass(frozen=True)
class DeploymentPlan:
    game_dir: Path
    mod_dir: Path
    files: dict[str, str]
    hashes: dict[str, str]
    warnings: tuple[str, ...] = ()


class LuaComposer:
    """The single composer used by the manager and installer."""

    def __init__(self, base_dir: Path):
        self.base_dir = Path(base_dir)

    @staticmethod
    def lua_value(value: Any) -> str:
        if isinstance(value, bool): return "true" if value else "false"
        if isinstance(value, (int, float)): return str(value)
        if isinstance(value, str): return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
        if isinstance(value, dict): return "{" + ", ".join(f'[{LuaComposer.lua_value(k)}] = {LuaComposer.lua_value(v)}' for k, v in value.items()) + "}"
        if isinstance(value, (list, tuple)): return "{" + ", ".join(LuaComposer.lua_value(v) for v in value) + "}"
        return "nil"

    def compose(self, modules: dict[str, dict[str, Any]], config: dict[str, Any]) -> str:
        enabled = config.get("enabled_modules", {})
        settings = config.get("module_settings", {})
        selected_ids = {mid for mid in modules if enabled.get(mid, False)}
        graph = ModuleGraphService(self.base_dir / "modules").build(selected_ids)
        graph_errors = [issue.message for issue in graph.issues if issue.severity == "error"]
        if graph_errors:
            raise InstallerError("Module graph is not deployable: " + "; ".join(graph_errors))
        selected = [(mid, modules[mid]) for mid in graph.order if mid in modules and mid in selected_ids]
        seen: dict[str, str] = {}
        for mid, mod in selected:
            for resource in mod.get("resource_edits", mod.get("target_kfc_resources", [])):
                key = str(resource).lower()
                owner = seen.get(key)
                # target_kfc_resources describes compatible reads in the legacy
                # manifests, so only explicit resource_edits are conflicts.
                if owner and "resource_edits" in mod:
                    raise InstallerError(f"Conflicting resource edit '{resource}' declared by {owner} and {mid}; disable one module or make the edit explicit.")
                if "resource_edits" in mod: seen[key] = mid
        lines = ["-- Generated by Enshrouded Mod Hub Control Center", "-- DO NOT EDIT DIRECTLY", "", "local function safe_require(name)", "    local ok, result = pcall(require, name)", "    if not ok then print('[ModBrain ERROR] Config load failed: ' .. tostring(name) .. ' :: ' .. tostring(result)); return {} end", "    return result or {}", "end", "", "local Brain = {", "    Modules = {},", "    Configs = {},", "    Context = {", "        Log = function(msg) print('[ModBrain] ' .. tostring(msg)) end,", "        LogWarn = function(msg) print('[ModBrain WARN] ' .. tostring(msg)) end,", "        LogError = function(msg) print('[ModBrain ERROR] ' .. tostring(msg)) end,", "        GetResources = function(typeName) if game and game.assets and game.assets.get_resources_by_type then return game.assets.get_resources_by_type(typeName) or {} end return {} end,", "    }", "}", ""]
        for mid, _ in selected:
            lines.append(f"Brain.Configs['{mid}'] = safe_require('Config.{mid}')")
        lines.append("")
        for mid, mod in selected:
            entry = Path(mod["_path"]) / mod.get("entrypoint", "patch.lua")
            if not entry.is_file():
                raise InstallerError(f"Enabled module '{mid}' is missing entrypoint: {entry}")
            lines += [f"-- Module: {mid}", "local ok, err = pcall(function()", "    local modFunc = function()"]
            lines += ["        " + line for line in entry.read_text(encoding="utf-8").splitlines()]
            lines += ["    end", "    local instance = modFunc()", f"    if instance and instance.OnInit then instance.OnInit(Brain.Configs['{mid}'] or {{}}, Brain.Context) end", f"    Brain.Modules['{mid}'] = instance", "end)", "if not ok then", f"    Brain.Context.LogError('Module {mid} failed safely: ' .. tostring(err))", "end", ""]
        return "\n".join(lines)

    def config_files(self, modules: dict[str, dict[str, Any]], config: dict[str, Any]) -> dict[str, str]:
        """Return one EML-loadable config module per enabled Control Center module."""
        enabled = config.get("enabled_modules", {})
        settings = config.get("module_settings", {})
        files: dict[str, str] = {}
        selected_ids = {mid for mid in modules if enabled.get(mid, False)}
        graph = ModuleGraphService(self.base_dir / "modules").build(selected_ids)
        graph_errors = [issue.message for issue in graph.issues if issue.severity == "error"]
        if graph_errors:
            raise InstallerError("Module graph is not deployable: " + "; ".join(graph_errors))
        for mid in graph.order:
            if mid not in modules or mid not in selected_ids:
                continue
            payload = settings.get(mid, {})
            files[f"src/Config/{mid}.lua"] = "-- Generated by Control Center; do not edit directly.\nreturn " + self.lua_value(payload) + "\n"
        return files


class InstallerService:
    MOD_ID = "enshrouded_mod_hub"
    OWNER_FILE = ".emh-owner.json"

    def __init__(self, base_dir: Path, manager=None, staging_root: Optional[Path] = None):
        self.base_dir = Path(base_dir)
        self.manager = manager
        self.config_path = self.base_dir / "profiles" / "installer.json"
        self.staging_root = Path(staging_root) if staging_root else Path(os.environ.get("LOCALAPPDATA", tempfile.gettempdir())) / "EnshroudedModHub" / "staging"
        self.staging_root.mkdir(parents=True, exist_ok=True)

    def save_game_path(self, game_dir: Path) -> None:
        self.config_path.parent.mkdir(parents=True, exist_ok=True)
        self.config_path.write_text(json.dumps({"game_dir": str(Path(game_dir).resolve())}, indent=2), encoding="utf-8")

    def selected_game_path(self) -> Optional[Path]:
        if not self.config_path.is_file(): return None
        try: return Path(json.loads(self.config_path.read_text(encoding="utf-8"))["game_dir"])
        except (OSError, KeyError, ValueError, TypeError): return None

    def discover_steam_games(self) -> list[Path]:
        roots = [Path(os.environ.get("PROGRAMFILES(X86)", r"C:\Program Files (x86)")) / "Steam", Path(os.environ.get("PROGRAMFILES", r"C:\Program Files")) / "Steam"]
        result: set[Path] = set()
        for root in roots:
            for lib in [root / "steamapps"] + self._library_folders(root / "steamapps" / "libraryfolders.vdf"):
                candidate = lib / "common" / "Enshrouded"
                if (candidate / "Enshrouded.exe").is_file(): result.add(candidate)
        return sorted(result)

    @staticmethod
    def _library_folders(vdf: Path) -> list[Path]:
        if not vdf.is_file(): return []
        out = []
        for line in vdf.read_text(errors="ignore").splitlines():
            if '"path"' in line:
                raw = line.split('"')[-2].replace("\\\\", "\\")
                out.append(Path(raw) / "steamapps")
        return out

    def detect(self, game_dir: Path) -> dict[str, Any]:
        game_dir = Path(game_dir)
        mods = game_dir / "mods"
        proxies = [p for name in ("dinput8.dll", "version.dll", "winmm.dll", "dxgi.dll") if (p := game_dir / name).is_file()]
        return {"game_dir": game_dir, "mods_dir": mods, "eml_proxies": proxies, "has_game": (game_dir / "Enshrouded.exe").is_file(), "has_mods_dir": mods.is_dir()}

    def _running(self) -> bool:
        try:
            text = subprocess.check_output(["tasklist", "/FI", "IMAGENAME eq Enshrouded.exe"], text=True, stderr=subprocess.DEVNULL)
            return "Enshrouded.exe" in text
        except (OSError, subprocess.SubprocessError): return False

    def _source(self, game_dir: Path) -> tuple[dict, str, dict[str, str]]:
        if self.manager is None: raise InstallerError("Installer requires a ModuleManager")
        self.manager.discover_modules(); self.manager.load_profile()
        selected = {mid for mid in self.manager.modules
                    if self.manager.active_config.get("enabled_modules", {}).get(mid, False)}
        api_version = RuntimeHealthService().inspect(Path(game_dir)).loader_api_version
        graph = ModuleGraphService(self.base_dir / "modules", api_version).build(selected)
        problems = [f"{issue.module_id}: {issue.message}" for issue in graph.issues
                    if issue.severity == "error"]
        if api_version is None:
            problems.extend(f"{mid}: cannot confirm the required EML API version; launch the installed loader and rescan before deploying."
                            for mid in sorted(selected)
                            if self.manager.modules[mid].get("required_loader_api_version") is not None)
        if problems:
            raise InstallerError("Module compatibility check failed: " + "; ".join(problems))
        lua = LuaComposer(self.base_dir).compose(self.manager.modules, self.manager.active_config)
        manifest = {"id": self.MOD_ID, "name": "Enshrouded Mod Hub", "version": "1.0.2", "author": "Enshrouded Mod Hub", "entrypoint": "src/mod.lua", "capabilities": ["patch"], "feature_state": "stable", "generated": True}
        configs = LuaComposer(self.base_dir).config_files(self.manager.modules, self.manager.active_config)
        return manifest, lua, configs

    def validate(self, game_dir: Path) -> list[str]:
        info = self.detect(game_dir); errors = []
        if not info["has_game"]: errors.append("Enshrouded.exe was not found in the selected folder.")
        if info["eml_proxies"]: errors.append("Detected EML proxy: " + ", ".join(p.name for p in info["eml_proxies"]) + ". It will be preserved.")
        if self.manager is None: errors.append("No module manager is configured.")
        self._source(game_dir)
        return errors

    def preview(self, game_dir: Path) -> DeploymentPlan:
        manifest, lua, configs = self._source(game_dir)
        mod_dir = Path(game_dir) / "mods" / self.MOD_ID
        files = {"mod.json": json.dumps(manifest, indent=2) + "\n", "src/mod.lua": lua, **configs}
        try:
            parsed = json.loads(files["mod.json"])
            required = {"id", "name", "version", "author", "entrypoint", "capabilities", "feature_state"}
            if not required.issubset(parsed) or "patch" not in parsed["capabilities"]: raise InstallerError("Generated mod manifest is missing the required patch capability or feature state.")
            if parsed["feature_state"] != "stable": raise InstallerError("Generated stable hub manifest must declare feature_state=stable.")
            if Path(parsed["entrypoint"]).is_absolute() or ".." in Path(parsed["entrypoint"]).parts: raise InstallerError("Generated manifest entrypoint must be a safe relative path.")
        except json.JSONDecodeError as exc: raise InstallerError(f"Generated manifest is invalid JSON: {exc}") from exc
        hashes = {name: hashlib.sha256(data.encode()).hexdigest() for name, data in files.items()}
        return DeploymentPlan(Path(game_dir), mod_dir, files, hashes, tuple(self.detect(game_dir)["eml_proxies"] and ["Existing EML proxy files will not be changed."] or []))

    def install(self, game_dir: Path, progress: Optional[Callable[[str], None]] = None) -> DeploymentPlan:
        if self._running(): raise InstallerError("Installation is blocked while Enshrouded.exe is running.")
        errors = self.validate(game_dir)
        if errors and not all("preserved" in e.lower() for e in errors): raise InstallerError("; ".join(errors))
        plan = self.preview(game_dir)
        if plan.mod_dir.exists() and not (plan.mod_dir / self.OWNER_FILE).is_file():
            existing = [plan.mod_dir / rel for rel in plan.files if (plan.mod_dir / rel).exists()]
            if existing:
                raise InstallerError("Refusing to overwrite unowned Mod Hub package files: " + ", ".join(str(p) for p in existing))
        stamp = time.strftime("%Y%m%d-%H%M%S")
        backup = self.staging_root / "backups" / stamp; backup.mkdir(parents=True, exist_ok=True)
        stage = Path(tempfile.mkdtemp(prefix="install-", dir=self.staging_root))
        created: list[Path] = []
        had_owned_mod = plan.mod_dir.exists() and (plan.mod_dir / self.OWNER_FILE).is_file()
        snapshot = backup / "snapshot"
        try:
            # Snapshot the complete owned package before any stale-file cleanup
            # or replacement. This is the rollback source of truth, including
            # files from the previous deployment that the new plan omits.
            if had_owned_mod:
                shutil.copytree(plan.mod_dir, snapshot)
            # Remove stale generated per-module configs when a module has been
            # disabled. The package is owner-controlled, so this cannot touch
            # third-party mod directories or unrelated game files.
            config_dir = plan.mod_dir / "src" / "Config"
            if plan.mod_dir.exists() and (plan.mod_dir / self.OWNER_FILE).is_file() and config_dir.is_dir():
                expected = {Path(rel).name for rel in plan.files if rel.startswith("src/Config/")}
                for stale in config_dir.glob("*.lua"):
                    if stale.name not in expected:
                        stale.unlink()
            for rel, data in plan.files.items():
                target = plan.mod_dir / rel; target.parent.mkdir(parents=True, exist_ok=True)
                if target.exists():
                    (backup / rel).parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(target, backup / rel)
                else:
                    created.append(target)
                staged = stage / rel; staged.parent.mkdir(parents=True, exist_ok=True); staged.write_bytes(data.encode("utf-8"))
                shutil.copy2(staged, target)
                if progress: progress(f"Installed {rel}")
            previous_owner = {}
            owner_path = plan.mod_dir / self.OWNER_FILE
            if owner_path.is_file():
                try:
                    previous_owner = json.loads(owner_path.read_text(encoding="utf-8-sig"))
                except (OSError, ValueError, TypeError):
                    previous_owner = {}
            owner = {
                "owner": self.MOD_ID,
                "installed_at": time.time(),
                "updated_by": "control_center",
                "files": plan.hashes,
                "previous_files": previous_owner.get("files", {}),
                "backup": str(backup),
            }
            (plan.mod_dir / self.OWNER_FILE).write_text(json.dumps(owner, indent=2), encoding="utf-8")
            self.save_game_path(plan.game_dir)
            self.verify(plan.game_dir)
            return plan
        except Exception:
            if snapshot.is_dir():
                shutil.rmtree(plan.mod_dir, ignore_errors=True)
                shutil.copytree(snapshot, plan.mod_dir)
            else:
                shutil.rmtree(plan.mod_dir, ignore_errors=True)
            raise
        finally: shutil.rmtree(stage, ignore_errors=True)

    def _restore(self, mod_dir: Path, backup: Path) -> None:
        if not backup.exists(): return
        for p in backup.rglob("*"):
            if p.is_file():
                rel = p.relative_to(backup); target = mod_dir / rel; target.parent.mkdir(parents=True, exist_ok=True); shutil.copy2(p, target)

    def verify(self, game_dir: Path) -> bool:
        plan = self.preview(game_dir); owner = plan.mod_dir / self.OWNER_FILE
        if not owner.is_file(): raise InstallerError("Ownership manifest is missing after installation.")
        data = json.loads(owner.read_text(encoding="utf-8"))
        for rel, digest in data.get("files", {}).items():
            p = plan.mod_dir / rel
            if not p.is_file() or hashlib.sha256(p.read_bytes()).hexdigest() != digest: raise InstallerError(f"Verification failed for owned file: {rel}")
        return True

    def repair(self, game_dir: Path, progress=None) -> DeploymentPlan: return self.install(game_dir, progress)

    def uninstall(self, game_dir: Path) -> None:
        if self._running(): raise InstallerError("Uninstall is blocked while Enshrouded.exe is running.")
        mod_dir = Path(game_dir) / "mods" / self.MOD_ID; owner = mod_dir / self.OWNER_FILE
        if not owner.is_file(): raise InstallerError("Ownership manifest not found; refusing to remove unowned files.")
        data = json.loads(owner.read_text(encoding="utf-8"))
        for rel in data.get("files", {}):
            p = mod_dir / rel
            if p.is_file(): p.unlink()
        owner.unlink()
        # Remove only empty directories created by this package, including the
        # separate src/Config tree used by the EML deployment format.
        for d in sorted((p for p in mod_dir.rglob("*") if p.is_dir()), key=lambda p: len(p.parts), reverse=True):
            try: d.rmdir()
            except OSError: pass
        try: mod_dir.rmdir()
        except OSError: pass
