-- Generated by Enshrouded Control Center KFC Research Lab.
-- Reversible scalar write/readback/revert probe.
local BUILD = '1076226'
local function log(result) print('[CC-WRITE-RESEARCH] ' .. result) end
local function test(resource_name, field_name, candidate_id, kind)
    local ok, resources = pcall(function() return game.assets.get_resources_by_type(resource_name) or {} end)
    if not ok or #resources == 0 then log(candidate_id .. '|resource_not_loaded'); return end
    local resource = resources[1]
    local read_ok, original = pcall(function() return resource.data[field_name] end)
    if not read_ok then log(candidate_id .. '|read_error|' .. tostring(original)); return end
    local test_value = original
    if kind == 'boolean' then test_value = not original end
    if kind == 'number' then test_value = original + 0.125 end
    if kind == 'integer' then test_value = original + 1 end
    local write_ok, write_error = pcall(function() resource.data[field_name] = test_value end)
    if not write_ok then log(candidate_id .. '|write_error|' .. tostring(write_error)); return end
    local readback_ok, readback = pcall(function() return resource.data[field_name] end)
    local restore_ok, restore_error = pcall(function() resource.data[field_name] = original end)
    local restored_ok, restored = pcall(function() return resource.data[field_name] end)
    log(table.concat({candidate_id, 'write=' .. tostring(write_ok), 'readback=' .. tostring(readback_ok), tostring(readback), 'restore=' .. tostring(restore_ok), 'restored=' .. tostring(restored_ok), tostring(restored)}, '|'))
    if not restore_ok then log(candidate_id .. '|restore_error|' .. tostring(restore_error)) end
end
log('BEGIN|build=' .. BUILD)
test('keen::BalancingTable', 'hookShotCostBase', 'keen::BalancingTable.hookShotCostBase', 'integer')
test('keen::BalancingTable', 'hookShotCostLevelFactor', 'keen::BalancingTable.hookShotCostLevelFactor', 'number')
test('keen::BalancingTable', 'itemLevelCap', 'keen::BalancingTable.itemLevelCap', 'integer')
test('keen::BalancingTable', 'killToLevelUPEnd', 'keen::BalancingTable.killToLevelUPEnd', 'integer')
test('keen::BalancingTable', 'killToLevelUPStart', 'keen::BalancingTable.killToLevelUPStart', 'integer')
test('keen::BalancingTable', 'levelDifferenceXpDamper', 'keen::BalancingTable.levelDifferenceXpDamper', 'number')
test('keen::BalancingTable', 'levelDifferenceXpModMax', 'keen::BalancingTable.levelDifferenceXpModMax', 'number')
test('keen::BalancingTable', 'levelDifferenceXpModMin', 'keen::BalancingTable.levelDifferenceXpModMin', 'number')
test('keen::BalancingTable', 'maximumInstrumentsCountedForComfort', 'keen::BalancingTable.maximumInstrumentsCountedForComfort', 'integer')
test('keen::BalancingTable', 'maximumTotalMusicComfortBuff', 'keen::BalancingTable.maximumTotalMusicComfortBuff', 'integer')
test('keen::BalancingTable', 'noiseRainFactor', 'keen::BalancingTable.noiseRainFactor', 'number')
test('keen::BalancingTable', 'perkCostCreep', 'keen::BalancingTable.perkCostCreep', 'number')
test('keen::BalancingTable', 'perkCostFactorArmor', 'keen::BalancingTable.perkCostFactorArmor', 'number')
test('keen::BalancingTable', 'perkCostFactorRings', 'keen::BalancingTable.perkCostFactorRings', 'number')
test('keen::BalancingTable', 'perkCostFactorWeaponsShield', 'keen::BalancingTable.perkCostFactorWeaponsShield', 'number')
test('keen::BalancingTable', 'perkPower', 'keen::BalancingTable.perkPower', 'number')
test('keen::BalancingTable', 'perkUpgradeCostSeed', 'keen::BalancingTable.perkUpgradeCostSeed', 'integer')
test('keen::BalancingTable', 'playerBaseFogResistance', 'keen::BalancingTable.playerBaseFogResistance', 'integer')
test('keen::BalancingTable', 'playerBaseHealth', 'keen::BalancingTable.playerBaseHealth', 'integer')
test('keen::BalancingTable', 'playerBaseMana', 'keen::BalancingTable.playerBaseMana', 'integer')
log('END|build=' .. BUILD)
