"""Generate an isolated EML probe for KFC/reflection candidates.

The default probe is read-only. It inventories resource presence, field
presence, Lua-visible type, and a sample value. Write tests are deliberately
opt-in because a reflected field is not automatically safe or authoritative.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CANDIDATES = ROOT / "research" / "kfc_tuning_candidates_2026-09-25.json"
DEFAULT_OUT = ROOT / "research" / "probes" / "kfc_read_probe_1076226"


def load_candidates(path: Path) -> list[dict]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    unique: dict[tuple[str, str], dict] = {}
    for item in payload.get("candidates", []):
        resource = item.get("target_resource")
        field = item.get("target_field")
        if resource and field:
            unique.setdefault((resource, field), item)
    return list(unique.values())


def lua_quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def build_lua(candidates: list[dict], build: str) -> str:
    lines = [
        "-- Generated by Enshrouded Control Center KFC Research Lab.",
        "-- READ-ONLY probe: no game values are written.",
        f"local BUILD = '{lua_quote(build)}'",
        "local function log(result) print('[CC-RESEARCH] ' .. result) end",
        "local function inspect(resource_name, field_name, candidate_id)",
        "    local ok, resources = pcall(function() return game.assets.get_resources_by_type(resource_name) or {} end)",
        "    if not ok then log(candidate_id .. '|resource_call_error|' .. tostring(resources)); return end",
        "    local count = 0",
        "    for _, resource in pairs(resources) do",
        "        count = count + 1",
        "        local read_ok, value = pcall(function()",
        "            local data = resource and resource.data",
        "            if data == nil then error('missing_data') end",
        "            return data[field_name]",
        "        end)",
        "        if read_ok then",
        "            log(table.concat({candidate_id, 'readable', tostring(count), type(value), tostring(value)}, '|'))",
        "        else",
        "            log(table.concat({candidate_id, 'field_error', tostring(count), tostring(value)}, '|'))",
        "        end",
        "    end",
        "    if count == 0 then log(candidate_id .. '|resource_not_loaded|0') end",
        "end",
        "log('BEGIN|build=' .. BUILD)",
    ]
    for item in candidates:
        resource = lua_quote(item["target_resource"])
        field = lua_quote(item["target_field"])
        cid = lua_quote(f"{item['target_resource']}.{item['target_field']}")
        lines.append(f"inspect('{resource}', '{field}', '{cid}')")
    lines.append("log('END|build=' .. BUILD)")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--candidates", type=Path, default=DEFAULT_CANDIDATES)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()
    candidates = load_candidates(args.candidates)
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / "src").mkdir(parents=True, exist_ok=True)
    build = json.loads(args.candidates.read_text(encoding="utf-8")).get("build", "unknown")
    manifest = {
        "id": "control_center_kfc_read_probe",
        "name": "Control Center KFC Read Probe",
        "version": "0.1.0",
        "author": "Enshrouded Control Center",
        "capabilities": ["patch"],
        "feature_state": "research-only",
        "entrypoint": "src/mod.lua",
        "research_build": build,
        "mode": "read_only",
        "candidate_count": len(candidates),
    }
    (args.output / "mod.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    (args.output / "src" / "mod.lua").write_text(build_lua(candidates, str(build)), encoding="utf-8")
    (args.output / "probe_manifest.json").write_text(json.dumps({"build": build, "candidates": candidates}, indent=2) + "\n", encoding="utf-8")
    print(f"Generated read-only probe: {args.output}")
    print(f"Unique resource/field candidates: {len(candidates)}")


if __name__ == "__main__":
    main()
